server:
  port: 8089
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: sms-group
    sendMessageTimeout: 300000

spring:
    #对rabbit的支持
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
        publisher-confirm-type: correlated
        listener:
            simple:
                retry:
                    enabled: true
        virtual-host: /myhost

