package sunhp.rules;

import com.sunhp.drools.entity.Address;
import com.sunhp.drools.entity.AddressCheckResult;


rule "Rules"
    when
        adress : Address(postCode != null,postCode matches "([0-9]{5})")
        checkResult: AddressCheckResult();
    then
        checkResult.setPostCodeResult(true);
        System.out.println("规则中打印日志：postCode校验通过");
end

rule "Rulese"
    when
        adress : Address(street != null)
        checkResult: AddressCheckResult();
    then
        checkResult.setPostCodeResult(true);
        System.out.println("规则中打印日志：street校验通过");
end